from researcher_network_mk.scraper.ukim_scrapers import (
    eccf_name_scraper,
    finki_name_scraper,
    mfs_staff_scraper,
    gf_name_scraper,
    feit_staff_scraper,
    med_name_scraper,
    praven_name_scraper,
    stom_name_scraper,
    tmf_name_scraper,
    farma_name_scraper,
    fzf_names_scraper,
    pedagoski_name_scraper,
    sport_name_scraper,
    muzicko_name_scraper,
    bio_name_scraper,
    geo_name_scraper,
    etno_name_scraper,
    mat_name_scraper,
    fizika_name_scraper,
    hemija_name_scraper,
    seizmologija_name_scraper,
    arh_name_scraper,
    ek_inst_names_scraper,
    fdtme_name_scraper,
    fdu_name_scraper,
    flf_name_scraper,
    flu_name_scraper,
    fzf_names_scraper,
    isppi_inst_name_scraper,
    istoc_inst_name_scraper,
    iziis_inst_name_scraper,
    pbf_name_scraper,
    sf_name_scraper,
    vet_name_scraper,
    zem_inst_name_scraper,
    fznh_name_scraper,
)

def main():
    eccf_name_scraper.main()
    finki_name_scraper.main()
    mfs_staff_scraper.main()
    gf_name_scraper.main()
    feit_staff_scraper.main()
    med_name_scraper.main()
    praven_name_scraper.main()
    stom_name_scraper.main()
    tmf_name_scraper.main()
    farma_name_scraper.main()
    pedagoski_name_scraper.main()
    sport_name_scraper.main()
    muzicko_name_scraper.main()
    bio_name_scraper.main()
    geo_name_scraper.main()
    etno_name_scraper.main()
    mat_name_scraper.main()
    fizika_name_scraper.main()
    hemija_name_scraper.main()
    seizmologija_name_scraper.main()
    arh_name_scraper.main()
    fdtme_name_scraper.main()
    fdu_name_scraper.main()
    flf_name_scraper.main()
    flu_name_scraper.main()
    fzf_names_scraper.main()
    pbf_name_scraper.main()
    sf_name_scraper.main()
    vet_name_scraper.main()
    fznh_name_scraper.main()
    ek_inst_names_scraper.main()
    isppi_inst_name_scraper.main()
    istoc_inst_name_scraper.main()
    iziis_inst_name_scraper.main()
    zem_inst_name_scraper.main()

if __name__ == "__main__":
    main()
